version: '3'
services:
  mysql:
    image: mysql:5.7.5
    environment:
        MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306"
    restart: always

  broker:
    image: eclipse-mosquitto
    hostname: "broker"
    ports:
      - "1883:1883"
    restart: always

  subscriber:
      image: mqttsubscriber:1.0
      expose:
        - "8080"
      links:
      - broker
      - healthchecker
      depends_on:
        - broker
      restart: always


  dbcreator:
    image: dbcreator:1.0
    depends_on:
        - mysql
    restart: always

  mailsender:
      image: mailsender:1.0
      expose:
        - "4000"
      restart: always
  dbconnector:
      image: dbconnector:1.0
      expose:
         - "7000"
      links:
      - mysql
      depends_on:
      - mysql
      restart: always

  cloudconnector:
      image: cloudconnector:1.0
      expose:
        - "6000"
      restart: always

  healthchecker:
      image: healthchecker:1.0
      expose:
        - "5000"
      links:
      - mailsender
      - cloudconnector
      - dbconnector
      restart: always



